---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


# List of resources
# https://kubectl.docs.kubernetes.io/references/kustomize/resource/
resources:
  - base/namespace.yaml
  - base/deploy.yaml
  - base/service.yaml


# Generator options
# https://kubectl.docs.kubernetes.io/references/kustomize/generatoroptions/
generatorOptions:
  labels:
    generator: "yes"


# Secret generators
# https://kubectl.docs.kubernetes.io/references/kustomize/secretgenerator/
# secretGenerator:
# - name: app-tls
#   files:
#   - secret/tls.cert
#   - secret/tls.key
#   type: "kubernetes.io/tls"
# - name: app-tls-namespaced
#   # you can define a namespace to generate
#   # a secret in, defaults to: "default"
#   namespace: apps
#   files:
#   - tls.crt=catsecret/tls.cert
#   - tls.key=secret/tls.key
#   type: "kubernetes.io/tls"
# - name: env_file_secret
#   envs:
#   - env.txt
#   type: Opaque
# - name: secret-with-annotation
#   files:
#   - app-config.yaml
#   type: Opaque
#   options:
#     annotations:
#       app_config: "true"
#     labels:
#       app.kubernetes.io/name: "app2"


# configmap generators
# configMapGenerator:
#   - name: hello-world
#     behavior: merge
#     files:
#       - application.properties
# - name: my-java-server-env-file-vars
#   envs:
#   - my-server-env.properties
#   - more-server-props.env
# - name: my-java-server-env-vars
#   literals:
#   - JAVA_HOME=/opt/java/jdk
#   - JAVA_TOOL_OPTIONS=-agentlib:hprof
#   options:
#     disableNameSuffixHash: true
#     labels:
#       pet: dog
# - name: dashboards
#   files:
#   - mydashboard.json
#   options:
#     annotations:
#       dashboard: "1"
#     labels:
#       app.kubernetes.io/name: "app1"

# vars:
#   - name: NAMESPACE
#     objref:
#       kind: namespace
#       name: hello-world
#       apiVersion: v1
#     fieldref:
#       fieldpath: metadata.name
#   - name: APP_NAME
#     objref:
#       kind: ConfigMap
#       name: hello-world
#       apiVersion: v1
#     fieldref:
#       fieldpath: data.labels_app
#   - name: APP_OWNER
#     objref:
#       kind: ConfigMap
#       name: hello-world
#       apiVersion: v1
#     fieldref:
#       fieldpath: data.labels_owner


# Add the below labels to all the resources
# https://kubectl.docs.kubernetes.io/references/kustomize/commonlabels/
commonLabels:
  app: hello-world
  owner: username


# Add the below annotations to all the resources
# https://kubectl.docs.kubernetes.io/references/kustomize/commonannotations/
commonAnnotations:
  zone: global


